/**
 * Data galeri Groomix — foto & video asli dari profil Google Maps
 * (folder public/photos & public/videos).
 * Placeholder blur digenerate via sharp (thumbnail 16px).
 */

export type GalleryPhoto = {
  src: string;
  w: number;
  h: number;
  blur: string;
  caption: string;
  alt: string;
};

const B1 =
  "/9j/2wBDABcQERQRDhcUEhQaGBcbIjklIh8fIkYyNSk5UkhXVVFIUE5bZoNvW2F8Yk5QcptzfIeLkpSSWG2grJ+OqoOPko3/2wBDARgaGiIeIkMlJUONXlBejY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY3/wAARCAAaABADASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAgQFAQP/xAAkEAADAAIBAgYDAAAAAAAAAAABAgMAEQQFIRIiMTJRgUFhkf/EABUBAQEAAAAAAAAAAAAAAAAAAAEC/8QAFhEBAQEAAAAAAAAAAAAAAAAAEQAB/9oADAMBAAIRAxEAPwBy4Z5SlNxMux7nfx+sldW4pkDV7yctvsoI1nfqlaLxpmZ05fwj7ByUwa01FgZqAxGzveTlWrCvKLJRWcqiMCn5+fTBjy0R5rTZmvY+XZA/uJD2feYcRh2//9k=";
const B2 =
  "/9j/2wBDABcQERQRDhcUEhQaGBcbIjklIh8fIkYyNSk5UkhXVVFIUE5bZoNvW2F8Yk5QcptzfIeLkpSSWG2grJ+OqoOPko3/2wBDARgaGiIeIkMlJUONXlBejY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY3/wAARCAAVABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAMEBf/EACMQAAIBAgYCAwAAAAAAAAAAAAECAwARBAUSEyExIkFhgbH/xAAUAQEAAAAAAAAAAAAAAAAAAAAC/8QAFxEBAQEBAAAAAAAAAAAAAAAAAAERMf/aAAwDAQACEQMRAD8A05syjjQuyrYfFYuZZmuLgTTGqm5BsOqRNFOxUGbUQ2kXsBc1M+HkXQCRxJZgPRv1R2FizExpuk253FY8/VJTy2ye2mBP7RRRh3r/2Q==";
const B3 =
  "/9j/2wBDABcQERQRDhcUEhQaGBcbIjklIh8fIkYyNSk5UkhXVVFIUE5bZoNvW2F8Yk5QcptzfIeLkpSSWG2grJ+OqoOPko3/2wBDARgaGiIeIkMlJUONXlBejY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY3/wAARCAAVABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAQC/8QAIhAAAgIBAwQDAAAAAAAAAAAAAQIDEQAEEiEiMUFxUVKB/8QAFAEBAAAAAAAAAAAAAAAAAAAAAv/EABYRAQEBAAAAAAAAAAAAAAAAAAARQf/aAAwDAQACEQMRAD8AjhhieO4JST9GF36rMFNxjUxlWdto5uz8ZJAdUJCY6iRD1S7ar98+sambeSyFlMZtLHJB84DxLqdXPMAkjkqvYZneXdAbvjm8YxQa/9k=";
const B4 =
  "/9j/2wBDABcQERQRDhcUEhQaGBcbIjklIh8fIkYyNSk5UkhXVVFIUE5bZoNvW2F8Yk5QcptzfIeLkpSSWG2grJ+OqoOPko3/2wBDARgaGiIeIkMlJUONXlBejY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY3/wAARCAAcABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAwUGBP/EACIQAAICAQQBBQAAAAAAAAAAAAECAxEABAUhQRIUMVFhsf/EABQBAQAAAAAAAAAAAAAAAAAAAAL/xAAYEQEBAQEBAAAAAAAAAAAAAAABAAIRIf/aAAwDAQACEQMRAD8AxQrGYmpqkB4X5w8KFGSQoHB5CnvANGqxGRrR2rx++8baHbfVaVJmlkt+xWAktMDUOyBLtfKxfWVe1q8u1RW/jRbkMQfzJWBVFCh7A4+0k7ppQoPAx5fY6OF//9k=";
const B5 =
  "/9j/2wBDABcQERQRDhcUEhQaGBcbIjklIh8fIkYyNSk5UkhXVVFIUE5bZoNvW2F8Yk5QcptzfIeLkpSSWG2grJ+OqoOPko3/2wBDARgaGiIeIkMlJUONXlBejY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY3/wAARCAAVABADASIAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAABAADBf/EAB4QAAICAgMBAQAAAAAAAAAAAAECAxEABBMhMUJx/8QAFAEBAAAAAAAAAAAAAAAAAAAAAv/EABkRAAMAAwAAAAAAAAAAAAAAAAABAhEhMf/aAAwDAQACEQMRAD8Adsby64lZQWAoUT5hdbaTZm5CpAI6F5lM7oJGeJZFc/TVWEAJlDBkUg9IvYwStifAbyvI1uxb9zoxRBlkkBrjUACvbyyw08DlJn//2Q==";
const B6 =
  "/9j/2wBDABcQERQRDhcUEhQaGBcbIjklIh8fIkYyNSk5UkhXVVFIUE5bZoNvW2F8Yk5QcptzfIeLkpSSWG2grJ+OqoOPko3/2wBDARgaGiIeIkMlJUONXlBejY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY3/wAARCAAWABADASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAMFBAb/xAAhEAACAgIBBAMAAAAAAAAAAAABAgMRAAQSBSExQSIjMv/EABQBAQAAAAAAAAAAAAAAAAAAAAP/xAAZEQADAQEBAAAAAAAAAAAAAAAAARECEiH/2gAMAwEAAhEDEQA/AKKcTNwH6q6r1jVldSyJHyryc5yFdnb3XeKRgqsfsvwL7Vlabcjh2pEk52SO4UkeBhz0SuGWKS4zGgCI638QAcR1J5V1wA5NsGJ9mhWGGPrK5oS07D//2Q==";
const B7 =
  "/9j/2wBDABcQERQRDhcUEhQaGBcbIjklIh8fIkYyNSk5UkhXVVFIUE5bZoNvW2F8Yk5QcptzfIeLkpSSWG2grJ+OqoOPko3/2wBDARgaGiIeIkMlJUONXlBejY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY3/wAARCAAdABADASIAAhEBAxEB/8QAGAAAAgMAAAAAAAAAAAAAAAAAAgQBAwX/xAAkEAACAgEDBAIDAAAAAAAAAAABAgMRAAQSIQUTIjEyQVFSof/EABUBAQEAAAAAAAAAAAAAAAAAAAID/8QAFxEBAQEBAAAAAAAAAAAAAAAAAQACEf/aAAwDAQACEQMRAD8A0BO5PxxDWvIZDfxAsVjM7mFVFeUhpB+cS1MoZbdtzbfeHsgjngTRHuDcyKvkWfkk8AD+4UKRasTGlYMGKjdew1yMnqKLKio6g9wbefqvRyro4CkLQpVAHH7CzksqlfWQ1f/Z";
const B8 =
  "/9j/2wBDABcQERQRDhcUEhQaGBcbIjklIh8fIkYyNSk5UkhXVVFIUE5bZoNvW2F8Yk5QcptzfIeLkpSSWG2grJ+OqoOPko3/2wBDARgaGiIeIkMlJUONXlBejY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY3/wAARCAAaABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAMF/8QAIxAAAQQBBAIDAQAAAAAAAAAAAQIDBBEABRIhMRNxFTJBsf/EABYBAQEBAAAAAAAAAAAAAAAAAAIAA//EABcRAQEBAQAAAAAAAAAAAAAAAAEAMSH/2gAMAwEAAhEDEQA/AJ6bOYlW27FaLoBVur7c4hxcdTzCWmWkq8yeUjnvMaE2uLvcU2VlQ2V77xOngiXHBSUhToIB/BRzNDZ9h/IuKBB2pBuq4q8fp8jzTWdyulA9dUki/wCYCEkGUgEAisu6Sl5VEj1iQyhdv//Z";
const B9 =
  "/9j/2wBDABcQERQRDhcUEhQaGBcbIjklIh8fIkYyNSk5UkhXVVFIUE5bZoNvW2F8Yk5QcptzfIeLkpSSWG2grJ+OqoOPko3/2wBDARgaGiIeIkMlJUONXlBejY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY3/wAARCAAWABADASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAQFAQL/xAAlEAADAAIBAgUFAAAAAAAAAAABAgMAEQQSIQUTFDGhIkFRYXH/xAAVAQEBAAAAAAAAAAAAAAAAAAACA//EABkRAAIDAQAAAAAAAAAAAAAAAAABAiExMv/aAAwDAQACEQMRAD8AZl4rxq1pEqVWY7ufYaPxkuBm3LnZqIqybfc+4zheG9Nv6lROg3Qa+pf1mrweLFZtShdX2etW+341k6KWVKTSlSXBPSew32xe0RSXlqelgOkMB8fzDDFDlBlrP//Z";
const B10 =
  "/9j/2wBDABcQERQRDhcUEhQaGBcbIjklIh8fIkYyNSk5UkhXVVFIUE5bZoNvW2F8Yk5QcptzfIeLkpSSWG2grJ+OqoOPko3/2wBDARgaGiIeIkMlJUONXlBejY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY3/wAARCAAUABADASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAMFAQT/xAAgEAACAwABBAMAAAAAAAAAAAABAgADESEEEjFRFEHw/8QAFQEBAQAAAAAAAAAAAAAAAAAAAgP/xAAYEQEAAwEAAAAAAAAAAAAAAAAAARExEv/aAAwDAQACEQMRAD8Al9Oz7Up1SG5JODPwjutsrt72HaxU7g9fUl/Jcg+G3N2NW1WtsVNKsoHqT5O3NbgtYAYOOBNqUFiefEIRxgzr/9k=";
const B11 =
  "/9j/2wBDABcQERQRDhcUEhQaGBcbIjklIh8fIkYyNSk5UkhXVVFIUE5bZoNvW2F8Yk5QcptzfIeLkpSSWG2grJ+OqoOPko3/2wBDARgaGiIeIkMlJUONXlBejY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY3/wAARCAAaABADASIAAhEBAxEB/8QAGAABAAMBAAAAAAAAAAAAAAAABQIDBAb/xAAjEAACAQMEAQUAAAAAAAAAAAABAgMABBEFEiFBIzJRceHw/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAL/xAAYEQEBAAMAAAAAAAAAAAAAAAARAAEhMf/aAAwDAQACEQMRAD8AytcqNb2KyRQlxu6A45pLUoYE09prSRS2cBlOe65u2tWvJizqypjk47q+4kFnCbaMDa2DnskVOkqMjMNFK6NucFTwExgL8Yo680t5oRIhxIoxtJ4P3SynxD97VNfUR1tpyX//2Q==";
const B12 =
  "/9j/2wBDABcQERQRDhcUEhQaGBcbIjklIh8fIkYyNSk5UkhXVVFIUE5bZoNvW2F8Yk5QcptzfIeLkpSSWG2grJ+OqoOPko3/2wBDARgaGiIeIkMlJUONXlBejY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY3/wAARCAAcABADASIAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAABQQBAv/EACMQAAICAgEDBQEAAAAAAAAAAAECAwQAERIFIUETFCIxYVH/xAAWAQEBAQAAAAAAAAAAAAAAAAACAQP/xAAWEQADAAAAAAAAAAAAAAAAAAAAARH/2gAMAwEAAhEDEQA/AJLQSnGkisWDkgo3gj+HEoaLz1VlVuCuobhgnUmM10VuWismu/7iSzTUkUz2C0Q0oCrrtmbGgm1PH7ksIleQ6JYn6zL/AFRrKcEULGT5+x+ZxRrpanseoT8ULDR85LG5RuQAOgexGxiipK4f/9k=";
const B13 =
  "/9j/2wBDABcQERQRDhcUEhQaGBcbIjklIh8fIkYyNSk5UkhXVVFIUE5bZoNvW2F8Yk5QcptzfIeLkpSSWG2grJ+OqoOPko3/2wBDARgaGiIeIkMlJUONXlBejY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY3/wAARCAAcABADASIAAhEBAxEB/8QAGAAAAgMAAAAAAAAAAAAAAAAAAwQBAgX/xAAhEAEAAgICAgIDAAAAAAAAAAABAgMAEQQhEkEiM3GBkf/EABYBAQEBAAAAAAAAAAAAAAAAAAMBAv/EABcRAQEBAQAAAAAAAAAAAAAAAAEAEQL/2gAMAwEAAhEDEQA/AGbGdX3bOjS9GVrvlN8ao7X2Yvz+bOzgJaiKafb3g+HyLK6ayNfwTTM9fn95lGpQ0xIaIn8xO2dvDubaFj5GpRTZLNSJswdtcU7ME6x2Z50y/9k=";
const B14 =
  "/9j/2wBDABcQERQRDhcUEhQaGBcbIjklIh8fIkYyNSk5UkhXVVFIUE5bZoNvW2F8Yk5QcptzfIeLkpSSWG2grJ+OqoOPko3/2wBDARgaGiIeIkMlJUONXlBejY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY3/wAARCAAbABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAwQFBv/EACQQAAIBAwIGAwAAAAAAAAAAAAECAwAEEQUhEhQiQVFxEzOB/8QAFAEBAAAAAAAAAAAAAAAAAAAAAv/EABcRAAMBAAAAAAAAAAAAAAAAAAABETH/2gAMAwEAAhEDEQA/AFZNRhiIcxkkH62O3vNVNDvY9RMiCIo6Lk9wf2ojW0eoBJ4s4RQr57tVvRQkHycCgdFCrBx6ZrnbmGRxHIRxHcHByfPujWt/PzMPWq9WG7ZFJXKBJ2VRtQsnzSiDWf/Z";
const B15 =
  "/9j/2wBDABcQERQRDhcUEhQaGBcbIjklIh8fIkYyNSk5UkhXVVFIUE5bZoNvW2F8Yk5QcptzfIeLkpSSWG2grJ+OqoOPko3/2wBDARgaGiIeIkMlJUONXlBejY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY3/wAARCAAMABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAAD/8QAHxAAAgICAwADAAAAAAAAAAAAAQIEEQMhABIiMTLx/8QAFAEBAAAAAAAAAAAAAAAAAAAAA//EABYRAAMAAAAAAAAAAAAAAAAAAAABMv/aAAwDAQACEQMRAD8ADGk48USPZoFHDELe71zORn7Q5Cswb0Ohrf25QyEjjwp0dkXw8nIc2J3ZVUkrfUV8fvBVCuT/2Q==";
const B16 =
  "/9j/2wBDABcQERQRDhcUEhQaGBcbIjklIh8fIkYyNSk5UkhXVVFIUE5bZoNvW2F8Yk5QcptzfIeLkpSSWG2grJ+OqoOPko3/2wBDARgaGiIeIkMlJUONXlBejY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY3/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAgMF/8QAHxAAAgICAgMBAAAAAAAAAAAAAQIDEQAEIUESEzFR/8QAFAEBAAAAAAAAAAAAAAAAAAAAA//EABYRAQEBAAAAAAAAAAAAAAAAAAEAEf/aAAwDAQACEQMRAD8AHDK9TK/riuxVki6y+1D4ajuu0zMoFgEXZ6IrjMCOaRWMcjgItE12fzHpSpLsOXJYBS1H4TxWGAEmq3//2Q==";
const B17 =
  "/9j/2wBDABcQERQRDhcUEhQaGBcbIjklIh8fIkYyNSk5UkhXVVFIUE5bZoNvW2F8Yk5QcptzfIeLkpSSWG2grJ+OqoOPko3/2wBDARgaGiIeIkMlJUONXlBejY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY3/wAARCAAcABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAwT/xAAiEAACAgIBAwUAAAAAAAAAAAABAgMRACEEBRIxE0FhccH/xAAWAQEBAQAAAAAAAAAAAAAAAAADAQL/xAAXEQEBAQEAAAAAAAAAAAAAAAABAAIh/9oADAMBAAIRAxEAPwCqLjoWYulVs3k3MjirugcMt+RgR9VjjWSrcue0Cq1WHxp2v0mXQ1oe+ZzntV5JFxkvez85bx0RJAwUXfnAjPdx4ZDoutmvsj8xl8jCFGZBL//Z";
const B18 =
  "/9j/2wBDABcQERQRDhcUEhQaGBcbIjklIh8fIkYyNSk5UkhXVVFIUE5bZoNvW2F8Yk5QcptzfIeLkpSSWG2grJ+OqoOPko3/2wBDARgaGiIeIkMlJUONXlBejY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY3/wAARCAAXABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAMEAv/EACMQAAIBBAEEAwEAAAAAAAAAAAECAwAEESESExQxQQUiUYH/xAAVAQEBAAAAAAAAAAAAAAAAAAABAP/EABYRAQEBAAAAAAAAAAAAAAAAABEAAf/aAAwDAQACEQMRAD8AQnxkfcPFFKzYQuCMb3jFS3EDQsFYADO8bIFUjqR3ydF+A4sWJ1rPqk3t/wB6h5BVkRh4G3GfH8o0SsRoZblCwMTPyYYbJrccyCFEcH6NrA9ctg/tFFGzl//Z";
const B19 =
  "/9j/2wBDABcQERQRDhcUEhQaGBcbIjklIh8fIkYyNSk5UkhXVVFIUE5bZoNvW2F8Yk5QcptzfIeLkpSSWG2grJ+OqoOPko3/2wBDARgaGiIeIkMlJUONXlBejY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY3/wAARCAAaABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAgQFA//EACMQAAIBAwMEAwAAAAAAAAAAAAECAwAEERIhQQUTMWEiMnH/xAAVAQEBAAAAAAAAAAAAAAAAAAACA//EABYRAQEBAAAAAAAAAAAAAAAAABEAAf/aAAwDAQACEQMRAD8AOaFY4GljkR2SISFCcUv02ZZ370wVSCVjUHOSBmp9tHLNdaZC0aYJO22M+PdMQQm0my4cOiyN9fiRxg81Myo7Ky3h1FYdlU5z7FbHqQe3OoqcjdDx+VM8hxwB4ooSdB35pBkV2//Z";
const B20 =
  "/9j/2wBDABcQERQRDhcUEhQaGBcbIjklIh8fIkYyNSk5UkhXVVFIUE5bZoNvW2F8Yk5QcptzfIeLkpSSWG2grJ+OqoOPko3/2wBDARgaGiIeIkMlJUONXlBejY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY3/wAARCAAUABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAMEBf/EACEQAAICAQQCAwAAAAAAAAAAAAECAxEABAUSISJhMUHh/8QAFAEBAAAAAAAAAAAAAAAAAAAAAv/EABkRAQACAwAAAAAAAAAAAAAAAAARIRIiQv/aAAwDAQACEQMRAD8An0WpkeV0EKlk6byr1jZNRINQsMsKQq1ksDZrM/aZy243HHzLKwIP31+ZTv5C6wKtK3DoAfJsYMaKbM2mNY54+N9ciO/WO3OmkBYXdjDDDwcbv//Z";
const B21 =
  "/9j/2wBDABcQERQRDhcUEhQaGBcbIjklIh8fIkYyNSk5UkhXVVFIUE5bZoNvW2F8Yk5QcptzfIeLkpSSWG2grJ+OqoOPko3/2wBDARgaGiIeIkMlJUONXlBejY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY3/wAARCAAVABADASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAAUBAgME/8QAIxAAAgEEAQMFAAAAAAAAAAAAAQIDAAQREiEiccEFFTFBYf/EABUBAQEAAAAAAAAAAAAAAAAAAAID/8QAGBEAAwEBAAAAAAAAAAAAAAAAAAEhAhH/2gAMAwEAAhEDEQA/AOv1a7a3ijmRdiGxjuDSn3Ke7GjDXbpyv7xV1vJb9CjKNc5Q/ZwOfFbMogWBCg+RIzccc1PMg2u0RyxmM5DnzURztt1Et3NFFVQGf//Z";
const B22 =
  "/9j/2wBDABcQERQRDhcUEhQaGBcbIjklIh8fIkYyNSk5UkhXVVFIUE5bZoNvW2F8Yk5QcptzfIeLkpSSWG2grJ+OqoOPko3/2wBDARgaGiIeIkMlJUONXlBejY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY3/wAARCAAVABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAQFAv/EACMQAAIBBAIABwAAAAAAAAAAAAECAwAEESESQQUTIkJRcaH/xAAWAQEBAQAAAAAAAAAAAAAAAAACAQP/xAAXEQADAQAAAAAAAAAAAAAAAAAAAiEx/9oADAMBAAIRAxEAPwAt3ih8KS6ZTMORXDHZB1UmXy7W45tieEnICN+Huty3LQWbWhkVWiYMPcG71S0WZY3Lhg3eBnfzis1lG1givqYdbqsJXMxBbKMSOP1RRUfRJh//2Q==";
const B23 =
  "/9j/2wBDABcQERQRDhcUEhQaGBcbIjklIh8fIkYyNSk5UkhXVVFIUE5bZoNvW2F8Yk5QcptzfIeLkpSSWG2grJ+OqoOPko3/2wBDARgaGiIeIkMlJUONXlBejY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY3/wAARCAAaABADASIAAhEBAxEB/8QAFwABAAMAAAAAAAAAAAAAAAAABAECA//EACMQAAIBAgYDAQEAAAAAAAAAAAECAwARBAUSEyExYXGBFCL/xAAWAQEBAQAAAAAAAAAAAAAAAAADAAH/xAAYEQADAQEAAAAAAAAAAAAAAAAAARECEv/aAAwDAQACEQMRAD8AU+aGKOLUxuyiw+ULNMW82GQdFie/VCdHeOKdYWDMALgFioA7+1LxvNgzvsqlVFrdE3tajonJfEPMMuTD7UnNgAQbOB65rTdV1jSaN10gLrZNC+SaPmrt++X+jwRbnrihSSPJqLuzHyb1LNRr1Gf/2Q==";
const B24 =
  "/9j/2wBDABcQERQRDhcUEhQaGBcbIjklIh8fIkYyNSk5UkhXVVFIUE5bZoNvW2F8Yk5QcptzfIeLkpSSWG2grJ+OqoOPko3/2wBDARgaGiIeIkMlJUONXlBejY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY3/wAARCAAJABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAMF/8QAIxAAAgEDAQkAAAAAAAAAAAAAAQIRAAMEMQUhMkFRYXKBwf/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAWEQADAAAAAAAAAAAAAAAAAAAAERL/2gAMAwEAAhEDEQA/AMzCfJxYZbRnTd3Gv2ljabq5F204REhhMlj1j3SbHAKpzueNGtiIR//Z";
const B25 =
  "/9j/2wBDABcQERQRDhcUEhQaGBcbIjklIh8fIkYyNSk5UkhXVVFIUE5bZoNvW2F8Yk5QcptzfIeLkpSSWG2grJ+OqoOPko3/2wBDARgaGiIeIkMlJUONXlBejY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY3/wAARCAAXABADASIAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAABAABAv/EACUQAAEEAgAEBwAAAAAAAAAAAAEAAgMRBBITIXGBFDFBUVJh4f/EABUBAQEAAAAAAAAAAAAAAAAAAAID/8QAFxEBAQEBAAAAAAAAAAAAAAAAAQACEf/aAAwDAQACEQMRAD8AFG7izzRatqMgWOtJE0YMHD0bbAXFwdz7j080GCQR5eS8OGrnWSep/FmTmRbwmFxIZYcCbsEe6AT7Gmxnyu2B7Wu/B2PjyP2pSmaajgv/2Q==";
const B26 =
  "/9j/2wBDABcQERQRDhcUEhQaGBcbIjklIh8fIkYyNSk5UkhXVVFIUE5bZoNvW2F8Yk5QcptzfIeLkpSSWG2grJ+OqoOPko3/2wBDARgaGiIeIkMlJUONXlBejY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY3/wAARCAAkABADASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAAQBBQYC/8QAIRAAAgIBAwUBAAAAAAAAAAAAAQIDEQAEITESEyJBgVH/xAAVAQEBAAAAAAAAAAAAAAAAAAACA//EABgRAQEBAQEAAAAAAAAAAAAAAAEAAhEh/9oADAMBAAIRAxEAPwBGVIxEjRtZI8h+HIjXtOjyR2vIB9jOZIjp0R13DbUcaTTap1WQdHAIF8XxtgPSa8ZCXUJLOCOCqg/MvU1JTTQiNFcdv1V/czMcR6t6N5pFKdlBSnxomheUwDDfSoU2xoTP0gXhhk8Vt3//2Q==";
const B27 =
  "/9j/2wBDABcQERQRDhcUEhQaGBcbIjklIh8fIkYyNSk5UkhXVVFIUE5bZoNvW2F8Yk5QcptzfIeLkpSSWG2grJ+OqoOPko3/2wBDARgaGiIeIkMlJUONXlBejY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY3/wAARCAAVABADASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAQFAgP/xAAfEAACAgIDAAMAAAAAAAAAAAABAgMRACEEEjETUoH/xAAWAQEBAQAAAAAAAAAAAAAAAAAAAgP/xAAXEQEBAQEAAAAAAAAAAAAAAAAAAQIh/9oADAMBAAIRAxEAPwC4skU8YY0wPjDMsrJfVuy0Tv0ZNl5rFJV48boRoCq19hnCCZxGtu5hc1LIXvqP3zMpxchfjqZOMFLbYBi1bxl4O6x8MufjK9jWiaOGGKZf/9k=";

const rawPhotos = [
  { src: "/photos/photo-01.png", w: 977, h: 1610, blur: B1, caption: "Di kursi, siap dirapikan", alt: "Pelanggan duduk di kursi barber depan cermin di studio Groomix, Subang" },
  { src: "/photos/photo-02.jpg", w: 1440, h: 1920, blur: B2, caption: "Nunggu giliran di kursi", alt: "Dua pelanggan duduk di kursi barber studio Groomix, Subang" },
  { src: "/photos/photo-03.jpg", w: 1086, h: 1448, blur: B3, caption: "Barber Groomix saat kerja", alt: "Barber Groomix sedang bekerja mengatur rambut pelanggan" },
  { src: "/photos/photo-04.jpg", w: 1061, h: 1886, blur: B4, caption: "Interior studio siang hari", alt: "Interior studio Groomix dengan kursi barber dan cermin besar" },
  { src: "/photos/photo-05.jpg", w: 3060, h: 4080, blur: B5, caption: "Detail potong dari belakang", alt: "Hasil potong rambut dilihat dari belakang di studio Groomix" },
  { src: "/photos/photo-06.jpg", w: 2740, h: 3764, blur: B6, caption: "Cek hasil di cermin", alt: "Pelanggan memeriksa hasil potongan rambutnya di depan cermin" },
  { src: "/photos/photo-07.jpg", w: 1179, h: 2096, blur: B7, caption: "Santai di kursi", alt: "Pelanggan santai di kursi barber studio Groomix" },
  { src: "/photos/photo-08.png", w: 977, h: 1609, blur: B8, caption: "Barber menata rambut", alt: "Barber menata rambut pelanggan di bawah tulisan Groomix" },
  { src: "/photos/photo-09.png", w: 1059, h: 1486, blur: B9, caption: "Proses potong yang telaten", alt: "Barber Groomix memotong rambut pelanggan dengan gunting" },
  { src: "/photos/photo-10.png", w: 1122, h: 1402, blur: B10, caption: "Rapiin model anak muda", alt: "Barber menyelesaikan potongan rambut pelanggan muda" },
  { src: "/photos/photo-11.png", w: 976, h: 1611, blur: B11, caption: "Profil hasil potong", alt: "Tampilan samping hasil potongan rambut di studio Groomix" },
  { src: "/photos/photo-12.png", w: 941, h: 1672, blur: B12, caption: "Crew cut rapi", alt: "Pelanggan dengan potongan crew cut duduk di kursi barber" },
  { src: "/photos/photo-13.jpg", w: 899, h: 1599, blur: B13, caption: "Studio dari samping", alt: "Studio Groomix terlihat dari samping dengan kursi barber" },
  { src: "/photos/photo-14.png", w: 971, h: 1619, blur: B14, caption: "Hasil potong dari samping", alt: "Hasil potongan rambut terlihat dari samping di studio Groomix" },
  { src: "/photos/photo-15.png", w: 1448, h: 1086, blur: B15, caption: "Etalase depan Groomix", alt: "Etalase depan Groomix Barbershop dengan logo di kaca" },
  { src: "/photos/photo-16.png", w: 1254, h: 1254, blur: B16, caption: "Kursi barber klasik", alt: "Deretan kursi barber klasik di studio Groomix" },
  { src: "/photos/photo-17.jpg", w: 899, h: 1599, blur: B17, caption: "Suasana bagian dalam studio", alt: "Suasana bagian dalam studio Groomix dengan cermin dan kursi" },
  { src: "/photos/photo-18.png", w: 1044, h: 1507, blur: B18, caption: "Perawatan rambut", alt: "Pelanggan menjalani perawatan rambut dengan alat steamer" },
  { src: "/photos/photo-19.png", w: 992, h: 1586, blur: B19, caption: "Sedang dipotong", alt: "Barber Groomix memotong rambut pelanggan yang berselimut cape" },
  { src: "/photos/photo-20.png", w: 1114, h: 1412, blur: B20, caption: "Konsultasi sebelum potong", alt: "Barber dan pelanggan berdiskusi model potongan rambut" },
  { src: "/photos/photo-21.png", w: 1086, h: 1448, blur: B21, caption: "Fade dari belakang", alt: "Hasil potongan fade dilihat dari belakang kepala" },
  { src: "/photos/photo-22.png", w: 1103, h: 1426, blur: B22, caption: "Santai di kursi perawatan", alt: "Pelanggan santai di kursi perawatan rambut studio Groomix" },
  { src: "/photos/photo-23.png", w: 983, h: 1601, blur: B23, caption: "Pelanggan puas", alt: "Pelanggan tampak puas setelah potongan rambut selesai" },
  { src: "/photos/photo-24.jpg", w: 1006, h: 580, blur: B24, caption: "Sudut studio", alt: "Sudut studio Groomix dengan kursi barber dan meja alat" },
  { src: "/photos/photo-25.png", w: 1049, h: 1499, blur: B25, caption: "Potong di depan cermin", alt: "Barber memotong rambut pelanggan di depan cermin besar" },
  { src: "/photos/photo-26.jpg", w: 2080, h: 4624, blur: B26, caption: "Suasana sore hari", alt: "Suasana studio Groomix pada sore hari dengan cahaya hangat" },
  { src: "/photos/photo-27.jpg", w: 3072, h: 4096, blur: B27, caption: "Hasil akhir", alt: "Pelanggan dengan hasil potongan rambut akhir di studio Groomix" },
];

/**
 * Placeholder blur tersimpan sebagai base64 mentah — dibungkus menjadi
 * data URI di sini supaya next/image mendapat format yang benar.
 */
export const galleryPhotos: GalleryPhoto[] = rawPhotos.map((p) => ({
  ...p,
  blur: `data:image/jpeg;base64,${p.blur}`,
}));

/** Video asli dari profil Google Maps Groomix. */
export const galleryVideos = [
  "/videos/video-01.mp4",
  "/videos/video-02.mp4",
  "/videos/video-03.mp4",
  "/videos/video-04.mp4",
  "/videos/video-05.mp4",
  "/videos/video-06.mp4",
] as const;

/** Foto tunggal untuk section Tentang (etalase depan). */
export const aboutPhoto =
  galleryPhotos.find((p) => p.src === "/photos/photo-15.png") ?? galleryPhotos[0];
